spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sell


wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  #mpAppId: wx7fc92d6649c19a52
  #mpAppSecret: 764d67fb0bd036908a4039270a3ba9b5

  openAppId:
  openAppSecret:

  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl : http://cxqdev.natapp1.cc/sell/pay/notify

projecturl:
  wechatMpAuthorize: http://cxqdev.natapp1.cc
  wechatOpenAuthorize: http://cxqdev.natapp1.cc
  sell: http://cxqdev.natapp1.cc
logging:
  level:
    com.imooc.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
